import type { Metadata } from "next";
import "./globals.css";
import "../../public/scss/styles.scss";
import Main from "./components/main";

export const metadata: Metadata = {
  title: "Sentimeter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Main>{children}</Main>;
}
